### ISSUE TITLE
Event Item Drop - Question

### ISSUE THREAD

**Issue by ptonino1** [JuniorDark/RustyHearts-Server-Manager#4]
Hey brother!  Thanks for your hard work on this.  Wondering what does the Event Item Drop function do? I tried changing the number but it seems to have no effect.  It's no biggie, but I was a bit curious as I was wondering if it would suddenly spawn a Halloween event with NPCs and drops etc. Wishful thinking maybe haha.

Hope you're taking care of yourself, cheers.

**Comment by JuniorDark** [comment]
I currently don't know what Event Item Drop does, some values in the content control are still a mystery to me, I need to investigate further.

To activate events you need to edit some files/tables on the client/server, I will make a patch for each event when I figure out the files
